title: Manasi Malik
logo: /assets/img/logo.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: 
google_analytics:
theme: jekyll-theme-minimal

social_links:
  twitter: https://twitter.com/ManasiMalik
  linkedin: https://www.linkedin.com/in/manasi-malik/
