title: Personal Website
email: mmalik16@jhu.edu
description: >- # this means to ignore newlines until "baseurl:"
  To be Added
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manasimalik.com" # the base hostname & protocol for your site

theme: minima

# Build settings
markdown: kramdown

# Navigation links
nav_links:
  - name: Home
    link: /
  - name: CV
    link: /assets/cv.pdf
