title: Manasi Malik
logo: /assets/img/logo.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: 
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
